name: Generate Zip

on:
  workflow_dispatch:
    inputs:
      production:
        description: 'Is this a production build?'
        default: false
        type: boolean

jobs:
  generate-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: install bun on the runner
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: install pup
        run: composer -- pup

      - name: pup build
        run: composer -- pup build

      - name: pup check
        run: composer -- pup check

      - name: pup i18n
        run: composer -- pup i18n

      - name: get version
        if: ${{ inputs.production }}
        run: echo "VERSION=$(composer -- pup get-version)" >> $GITHUB_ENV

      - name: debug version (production)
        if: ${{ inputs.production }}
        run: echo "Production VERSION=${{ env.VERSION }}"

      - name: get dev version
        if: ${{ !inputs.production }}
        run: echo "VERSION=$(composer -- pup get-version --dev)" >> $GITHUB_ENV

      - name: debug version (dev)
        if: ${{ !inputs.production }}
        run: echo "Development VERSION=${{ env.VERSION }}"

      - name: get zip name
        run: echo "ZIP_NAME=$(composer -- pup zip-name ${{ env.VERSION }})" >> $GITHUB_ENV

      - name: debug zip name
        run: echo "ZIP_NAME=${{ env.ZIP_NAME }}"

      - name: debug before packaging
        run: |
          echo "Environment before packaging:"
          echo "Working directory: $(pwd)"
          echo "VERSION: ${{ env.VERSION }}"
          echo "ZIP_NAME: ${{ env.ZIP_NAME }}"
          echo "Directory structure:"
          find . -maxdepth 2 -type d | sort
          echo "Composer command:"
          echo "composer -- pup package ${{ env.VERSION }}"

      - name: pup package
        run: |
          set -x
          composer -- pup package ${{ env.VERSION }}
          echo "Exit code: $?"
          set +x

      - name: debug zip output detail
        run: |
          echo "Current directory: $(pwd)"
          echo "Looking for ZIP files in various locations:"
          echo ".pup-zip directory contents (if exists):"
          if [ -d ".pup-zip" ]; then
            ls -la .pup-zip/
            echo "Files in .pup-zip:"
            find .pup-zip -type f | sort
          else
            echo ".pup-zip directory does not exist!"
          fi
          
          echo "Looking for other possible ZIP locations:"
          find . -name "*.zip" | sort
          
          echo "Checking pup output directory structure:"
          find .pup* -type d 2>/dev/null || echo "No .pup* directories found"
          
          echo "Full ZIP expected path: $(pwd)/.pup-zip/${{ env.ZIP_NAME }}"
          if [ -f ".pup-zip/${{ env.ZIP_NAME }}" ]; then
            echo "ZIP file exists at expected location"
            ls -la .pup-zip/${{ env.ZIP_NAME }}
          else
            echo "ZIP file DOES NOT exist at expected location!"
          fi

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: .pup-zip/${{ env.ZIP_NAME }}