name: Generate Zip

on:
  workflow_dispatch:
    inputs:
      production:
        description: 'Is this a production build?'
        default: false
        type: boolean

jobs:
  generate-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: install bun on the runner
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: install pup
        run: composer -- pup

      - name: pup build
        run: composer -- pup build

      - name: pup check
        run: composer -- pup check

      - name: pup i18n
        run: composer -- pup i18n

      - name: get version
        if: ${{ inputs.production }}
        run: echo "VERSION=$(composer -- pup get-version)" >> $GITHUB_ENV

      - name: debug version (production)
        if: ${{ inputs.production }}
        run: echo "Production VERSION=${{ env.VERSION }}"

      - name: get dev version
        if: ${{ !inputs.production }}
        run: echo "VERSION=$(composer -- pup get-version --dev)" >> $GITHUB_ENV

      - name: debug version (dev)
        if: ${{ !inputs.production }}
        run: echo "Development VERSION=${{ env.VERSION }}"

      - name: get zip name
        run: echo "ZIP_NAME=$(composer -- pup zip-name ${{ env.VERSION }})" >> $GITHUB_ENV

      - name: debug zip name
        run: echo "ZIP_NAME=${{ env.ZIP_NAME }}"

      - name: pup package
        run:  composer -- pup package ${{ env.VERSION }}

      - name: debug zip output
        run: |
          echo "Current directory: $(pwd)"
          echo "ZIP output directory contents:"
          ls -la .pup-zip
          echo "Full ZIP path: $(pwd)/.pup-zip/${{ env.ZIP_NAME }}"

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: .pup-zip